/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_layout_disabled`; params?: Router.UnknownInputParams; } | { pathname: `/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/project-selection`; params?: Router.UnknownInputParams; } | { pathname: `/role-selection`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/analytics`; params?: Router.UnknownInputParams; } | { pathname: `/attendance`; params?: Router.UnknownInputParams; } | { pathname: `/attendance/success`; params?: Router.UnknownInputParams; } | { pathname: `/dpr/step1`; params?: Router.UnknownInputParams; } | { pathname: `/dpr/step2`; params?: Router.UnknownInputParams; } | { pathname: `/dpr/step3`; params?: Router.UnknownInputParams; } | { pathname: `/dpr/success`; params?: Router.UnknownInputParams; } | { pathname: `/invoicing`; params?: Router.UnknownInputParams; } | { pathname: `/material`; params?: Router.UnknownInputParams; } | { pathname: `/material/new`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_layout_disabled`; params?: Router.UnknownOutputParams; } | { pathname: `/dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/project-selection`; params?: Router.UnknownOutputParams; } | { pathname: `/role-selection`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/analytics`; params?: Router.UnknownOutputParams; } | { pathname: `/attendance`; params?: Router.UnknownOutputParams; } | { pathname: `/attendance/success`; params?: Router.UnknownOutputParams; } | { pathname: `/dpr/step1`; params?: Router.UnknownOutputParams; } | { pathname: `/dpr/step2`; params?: Router.UnknownOutputParams; } | { pathname: `/dpr/step3`; params?: Router.UnknownOutputParams; } | { pathname: `/dpr/success`; params?: Router.UnknownOutputParams; } | { pathname: `/invoicing`; params?: Router.UnknownOutputParams; } | { pathname: `/material`; params?: Router.UnknownOutputParams; } | { pathname: `/material/new`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/_layout_disabled${`?${string}` | `#${string}` | ''}` | `/dashboard${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/project-selection${`?${string}` | `#${string}` | ''}` | `/role-selection${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/analytics${`?${string}` | `#${string}` | ''}` | `/attendance${`?${string}` | `#${string}` | ''}` | `/attendance/success${`?${string}` | `#${string}` | ''}` | `/dpr/step1${`?${string}` | `#${string}` | ''}` | `/dpr/step2${`?${string}` | `#${string}` | ''}` | `/dpr/step3${`?${string}` | `#${string}` | ''}` | `/dpr/success${`?${string}` | `#${string}` | ''}` | `/invoicing${`?${string}` | `#${string}` | ''}` | `/material${`?${string}` | `#${string}` | ''}` | `/material/new${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_layout_disabled`; params?: Router.UnknownInputParams; } | { pathname: `/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/project-selection`; params?: Router.UnknownInputParams; } | { pathname: `/role-selection`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/analytics`; params?: Router.UnknownInputParams; } | { pathname: `/attendance`; params?: Router.UnknownInputParams; } | { pathname: `/attendance/success`; params?: Router.UnknownInputParams; } | { pathname: `/dpr/step1`; params?: Router.UnknownInputParams; } | { pathname: `/dpr/step2`; params?: Router.UnknownInputParams; } | { pathname: `/dpr/step3`; params?: Router.UnknownInputParams; } | { pathname: `/dpr/success`; params?: Router.UnknownInputParams; } | { pathname: `/invoicing`; params?: Router.UnknownInputParams; } | { pathname: `/material`; params?: Router.UnknownInputParams; } | { pathname: `/material/new`; params?: Router.UnknownInputParams; } | `/+not-found${`?${string}` | `#${string}` | ''}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
